name: release-main

on:
  release:
    types: [published]

jobs:

  deploy-docs:
    runs-on: [self-hosted, linux, x64, podman]
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force

